version: '3.9'

services:
  external-service:
    image: demo/external-service:0.0.1-SNAPSHOT
    container_name: external-service
    ports:
      - 9502:9502
#    networks:
#      - backend
#
#networks:
#  backend:
#    driver: bridge
