spring:
  application:
    name: demo-client

  config:
    import: optional:configserver:http://localhost:9500/api
#  cloud:
#    config:
#      name: demo-client

server:
  port: 9501
  servlet:
    context-path: /api


integration:
  demo:
    root-uri: http://container_name:9502/api
    message: Hello from local service
