spring:
  application:
    name: demo-client

  config:
    import: optional:configserver:http://172.17.0.1:9500/api
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 20

server:
  port: 9501
  servlet:
    context-path: /api


integration:
  demo:
    root-uri: http://container_name:9502/api
    message: Hello from local service
