spring:
  application:
    name: demo-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/thepipeman/cloud-demo-configuration
          skip-ssl-validation: true


server:
  port: 9500
  servlet:
    context-path: /api